@Matkul_API_HostAddress = http://localhost:5124

GET {{Matkul_API_HostAddress}}/api/linq-query/
Accept: application/json

POST {{Matkul_API_HostAddress}}/api/auth/login
Accept: application/json

POST {{Matkul_API_HostAddress}}/api/auth/register
Accept: application/json

POST {{Matkul_API_HostAddress}}/api/transaction/header
Accept: application/json

PUT {{Matkul_API_HostAddress}}/api/transaction/header/{id}
Accept: application/json

GET {{Matkul_API_HostAddress}}/api/transaction/header
Accept: application/json

###
